version: '3.8'

services:
  db:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: donnut
    ports:
      - "5432:5432"
